<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>AniNest.Contracts</AssemblyName>
    <RootNamespace>AniNest.Contracts</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\AniNest.Core\\AniNest.Core.csproj" />
  </ItemGroup>

</Project>
